# This is a basic workflow to help you get started with Actions

name: release-build-upload

# Controls when the workflow will run
on: 
  release:
    types: [ created ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-upload_windows-x64:
    runs-on: windows-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: install qt static
        uses: orestonce/install-qt@main
        with:
          version: Qt5.15.7-Windows-x86_64-MinGW8.1.0-staticFull-20221104
      - name: build
        run: |
          qmake && mingw32-make release
          dir release\TetrisGame-qt.exe
      - name: upload release
        uses: Guerra24/upload-to-release@v1
        with:
          name: TetrisGame-qt_${{ github.ref_name }}.exe
          path: release\TetrisGame-qt.exe
          repo-token: ${{ secrets.GITHUB_TOKEN }}